### ISSUE TITLE
why not match statement?

### ISSUE THREAD

**Issue by AzerothA** [DenialAdams/roland#104]
Hey, I was reading the `lex` file in `rolandc` and I realized that there are too many if statements, from what I've seen we can change that to match the statement easily, or it has a good reason behind it?

example:
https://github.com/DenialAdams/roland/blob/733478efa78dfe8e8f9ff73ca6f08d720f9c6a6e/rolandc/src/lex.rs#L735

**Comment by DenialAdams** [comment]
Hi, thanks for checking out Roland!

No, I don't think there is a good reason for not using match in a couple of places here. That being said, this sort of minor style choice doesn't really bother me :)

Next time I'm working in that code I'll consider changing it!
